# Site settings
title: Sayem Hoque
email: sayemhoque6(at)gmail.com
description: ""
baseurl: ""
url: "http://sayemmh.github.io"
twitter_username: quintorrislopez
github_username: sayemmh

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge